FROM docker.elastic.co/elasticsearch/elasticsearch:8.11.0

ENV discovery.type=single-node
ENV ES_JAVA_OPTS="-Xms512m -Xmx512m"
ENV xpack.security.enabled=false
ENV xpack.security.http.ssl.enabled=false

EXPOSE 9200

CMD ["elasticsearch"]